import type { SolutionEditorialContent } from '../types';

export const cafesAndBakeriesContent: SolutionEditorialContent = {
  category: 'BUSINESS SOLUTION',
  metadata: {
    title: 'Marketing Solution for Cafés, Coffee Bars & Artisan Bakeries — StreetCraft',
    description:
      'Fill quiet 3 PM afternoon slowdowns, move fresh evening bake batches, and drive weekend brunch walk-ins with coordinated 4-touchpoint local marketing.',
    ogTitle: 'Marketing for Cafés & Artisan Bakeries — StreetCraft',
    ogDescription:
      'Turn slow afternoon hours and warm oven batches into packed café tables and sold-out pastry counters.',
  },
  eyebrow: 'HOSPITALITY & ARTISAN BAKING',
  title: 'Cafés, Coffee Bars & Artisan Bakeries',
  tagline: 'Fill quiet 3:00 PM – 6:00 PM troughs and move fresh bakes before closing time.',
  description:
    'Cafés and bakeries face predictable operational realities: quiet mid-afternoon lulls, morning counter rushes, and daily perishable surplus. StreetCraft gives café owners a fast marketing operating engine to convert quiet hours into profitable customer visits.',
  metrics: [
    {
      value: '3:00 PM',
      label: 'Afternoon Reset Focus',
      sublabel: 'Targeted pour-over and pastry pairings during quiet work hours.',
    },
    {
      value: 'Oven-Fresh',
      label: 'Batch Drop Messaging',
      sublabel: 'Rapid 60-second broadcast when specialty loaves come out hot.',
    },
    {
      value: '4 Surfaces',
      label: 'Synchronized Workflow',
      sublabel: 'Google search, Instagram Reels, WhatsApp VIPs, and counter cards.',
    },
  ],
  heroCta: {
    primary: {
      label: 'Try Free Campaign Tool',
      href: '/free-tool',
    },
    secondary: {
      label: 'View Subscription Pricing',
      href: '/pricing',
    },
  },
  anatomy: {
    eyebrow: 'VERTICAL ANATOMY',
    title: 'How a Café Campaign Operates in Practice',
    description:
      'From oven timer to counter customer: an example of a coordinated afternoon café campaign generated by StreetCraft.',
    previewTitle: 'Café Afternoon Reset Campaign Blueprint',
    previewType: 'recipe',
    items: [
      {
        badge: 'OPERATIONAL TRIGGER',
        label: 'The Quiet Afternoon Window',
        text: '3:00 PM – 5:30 PM weekday trough when morning commuters are gone and tables are half-empty.',
        note: 'The exact operational pain point that needs immediate local footfall.',
      },
      {
        badge: 'MENU PAIRING',
        label: 'High-Margin Anchor Item',
        text: 'Pour-Over (Ethiopian Yirgacheffe) + Fresh Almond Croissant combo at an attractive package price.',
        note: 'Injects your stored signature roasts and pastry specialties automatically.',
      },
      {
        badge: '4-WAY EXECUTION',
        label: 'Simultaneous Output',
        text: 'Google update for nearby remote workers + Instagram Story video prompt + WhatsApp regular broadcast + A5 counter tent card.',
        note: 'All compiled together without switching between four different marketing tools.',
      },
    ],
  },
  capabilities: [
    {
      tag: 'QUIET HOURS',
      title: 'Afternoon Work-From-Café Resets',
      description:
        'Target local remote workers, freelancers, and neighborhood professionals with mid-day coffee resets and wifi-friendly work pairings.',
      bulletPoints: [
        'Pour-over and artisan pastry combo promotions',
        'Specific validity windows (e.g. 3 PM to 6 PM only)',
        'Clear wifi and seating cues that appeal to remote workers',
      ],
    },
    {
      tag: 'FRESH BATCHES',
      title: 'Oven-Fresh Batch Alerts',
      description:
        'When sourdough loaves, pain au chocolat, or focaccia come out of the oven, broadcast instant flash drops to move stock before the evening shift ends.',
      bulletPoints: [
        'Sensory descriptions that highlight warm, golden crusts',
        'Direct "Reply on WhatsApp to Reserve" mechanics',
        'Minimizes end-of-day bakery surplus and waste',
      ],
    },
    {
      tag: 'WEATHER TRIGGERS',
      title: 'Monsoon & Rainy Day Specials',
      description:
        'Activate cozy weather promotions—hot spiced lattes, cinnamon buns, and warm soup pairings—as soon as neighborhood weather shifts.',
      bulletPoints: [
        'Pre-configured comfort food and hot beverage templates',
        'Neighborhood landmark injection for quick sheltering visits',
        'Instant deployment in under 60 seconds',
      ],
    },
  ],
  playbook: [
    {
      step: 1,
      trigger: 'Afternoon Lull Approaching',
      action: 'Select "Afternoon Slow Hour Boost" and your signature pastry in StreetCraft.',
      outcome: 'Receive 4 synchronized marketing assets tailored for immediate deployment.',
    },
    {
      step: 2,
      trigger: 'Publish Digital Channels',
      action: 'Post the Google Business update, dispatch WhatsApp VIP drop, and post Instagram Story.',
      outcome: 'Reaches nearby neighbors and office workers within a 1.5 km radius.',
    },
    {
      step: 3,
      trigger: 'Place Counter Tent',
      action: 'Place the printed A5 card near the register for walk-in upselling.',
      outcome: 'Baristas know the promotion rules and upsell single coffees to combo orders.',
    },
    {
      step: 4,
      trigger: 'Shift Wrap-Up',
      action: 'Review pastry sales and save the campaign pack to your store vault.',
      outcome: 'Ready to re-deploy next week with one click.',
    },
  ],
  closingCta: {
    eyebrow: 'GROW YOUR CAFE',
    title: 'Fill Your Tables and Sell Out Your Bakes',
    description:
      'Generate your first coordinated café campaign pack across Google, Instagram, WhatsApp, and counter print in 60 seconds.',
    primaryCta: {
      label: 'Try Free Campaign Tool',
      href: '/free-tool',
    },
    secondaryCta: {
      label: 'View Subscription Pricing',
      href: '/pricing',
    },
  },
};
