import type { SolutionEditorialContent } from '../types';

export const restaurantsAndFoodContent: SolutionEditorialContent = {
  category: 'BUSINESS SOLUTION',
  metadata: {
    title: 'Marketing Solution for Restaurants, Bistros & Food Outlets — StreetCraft',
    description:
      'Pack slow midweek dining tables, launch chef tasting specials, and capture festival dining pre-orders with coordinated 4-touchpoint local marketing.',
    ogTitle: 'Marketing for Restaurants & Bistros — StreetCraft',
    ogDescription:
      'Turn slow Tuesday nights, festival menus, and chef tasting drops into full dining rooms and high-margin table reservations.',
  },
  eyebrow: 'DINING & CASUAL HOSPITALITY',
  title: 'Restaurants, Bistros & Food Outlets',
  tagline: 'Pack slow Tuesday dinner services and launch chef specials without agency friction.',
  description:
    'Independent restaurants and bistros struggle with severe midweek dining dips and heavy commission fees from delivery aggregators. StreetCraft helps restaurant owners drive direct dine-in reservations and walk-in footfall across four coordinated touchpoints.',
  metrics: [
    {
      value: 'Midweek Focus',
      label: 'Tuesday / Wednesday Boost',
      sublabel: 'Engineered to fill open tables during slow weekday dinner services.',
    },
    {
      value: 'Direct Dining',
      label: 'Zero Aggregator Commissions',
      sublabel: 'Drives physical dine-in guests rather than discounted delivery orders.',
    },
    {
      value: 'Festival Sync',
      label: 'Regional Calendar Engine',
      sublabel: 'Automatic detection of upcoming cultural feasts and holiday weekends.',
    },
  ],
  heroCta: {
    primary: {
      label: 'Try Free Campaign Tool',
      href: '/free-tool',
    },
    secondary: {
      label: 'View Subscription Pricing',
      href: '/pricing',
    },
  },
  anatomy: {
    eyebrow: 'VERTICAL ANATOMY',
    title: 'How a Restaurant Campaign Operates in Practice',
    description:
      'From kitchen prep to packed dinner service: an example of a coordinated midweek restaurant promotion generated by StreetCraft.',
    previewTitle: 'Midweek Chef Tasting Special Blueprint',
    previewType: 'recipe',
    items: [
      {
        badge: 'OPERATIONAL TRIGGER',
        label: 'Midweek Table Availability',
        text: 'Tuesday & Wednesday 7:00 PM – 9:30 PM dinner service with multiple open 4-top tables.',
        note: 'The primary target for improving kitchen labor efficiency and revenue.',
      },
      {
        badge: 'CHEF SPECIAL',
        label: 'Signature Tasting Course',
        text: '3-Course Chef Tasting Menu featuring house specials paired with a welcome beverage at a fixed price.',
        note: 'Injects your restaurant’s signature cuisine and dietary highlights automatically.',
      },
      {
        badge: '4-WAY EXECUTION',
        label: 'Synchronized Channel Blast',
        text: 'Google event card with reservation button + Instagram Reel hook + WhatsApp VIP table invite + Table talker card.',
        note: 'Ensures the kitchen staff and floor servers are completely aligned.',
      },
    ],
  },
  capabilities: [
    {
      tag: 'MIDWEEK BOOST',
      title: 'Slow Night Dining Specials',
      description:
        'Fill your dining room on traditionally slow weekday evenings with chef tasting menus, complimentary dessert pairings, and group dining incentives.',
      bulletPoints: [
        'Dine-in exclusive pricing that protects direct restaurant margins',
        'Specific reservation windows that balance kitchen flow',
        'Direct phone and table reservation links',
      ],
    },
    {
      tag: 'FESTIVAL MENUS',
      title: 'Festival Feasts & Thali Pre-Orders',
      description:
        'Our date-aware calendar automatically prepares multi-channel campaigns for upcoming national and regional festivals weeks before the holiday rush.',
      bulletPoints: [
        'Pre-order deadlines and family platter reservations',
        'Festive storytelling copy honoring local culinary traditions',
        'Synchronized across search, social, and in-store chalkboards',
      ],
    },
    {
      tag: 'WEEKEND BRUNCH',
      title: 'Weekend Rush & Table Talker Signage',
      description:
        'Maximize average ticket sizes during busy weekend rushes with high-margin appetizer and dessert tent cards on every dining table.',
      bulletPoints: [
        'Formatted table tents that drive beverage and dessert add-ons',
        'QR code display for instant Google review capture at checkout',
        'Clear staff instructions for floor servers',
      ],
    },
  ],
  playbook: [
    {
      step: 1,
      trigger: 'Tuesday Reservation Lull',
      action: 'Select "Midweek Table Pack" and enter your featured chef special in StreetCraft.',
      outcome: 'Receive 4 synchronized marketing assets tailored for dinner service.',
    },
    {
      step: 2,
      trigger: 'Publish Early Afternoon',
      action: 'Post the Google Business event update and dispatch WhatsApp VIP table alert at 12:30 PM.',
      outcome: 'Captures professionals planning their evening dinner plans.',
    },
    {
      step: 3,
      trigger: 'Dinner Service Check-In',
      action: 'Floor staff welcomes guests and presents the printed table card with the featured tasting course.',
      outcome: 'Guests order the higher-margin chef special, boosting average table spend.',
    },
    {
      step: 4,
      trigger: 'Post-Meal Review',
      action: 'Guests scan the table card QR code to leave an instant 5-star Google review.',
      outcome: 'Strengthens local search map rankings for future dinner services.',
    },
  ],
  closingCta: {
    eyebrow: 'GROW YOUR RESTAURANT',
    title: 'Fill Your Tables Every Night of the Week',
    description:
      'Generate your first coordinated restaurant campaign pack across Google, Instagram, WhatsApp, and counter print in 60 seconds.',
    primaryCta: {
      label: 'Try Free Campaign Tool',
      href: '/free-tool',
    },
    secondaryCta: {
      label: 'View Subscription Pricing',
      href: '/pricing',
    },
  },
};
