import type { SolutionEditorialContent } from '../types';

export const retailAndBoutiquesContent: SolutionEditorialContent = {
  category: 'BUSINESS SOLUTION',
  metadata: {
    title: 'Marketing Solution for Retail Boutiques & Lifestyle Stores — StreetCraft',
    description:
      'Launch new apparel arrival unboxings, drive weekend clearance footfall, and host VIP shopping preview events with coordinated 4-touchpoint local marketing.',
    ogTitle: 'Marketing for Retail Boutiques & Lifestyle Stores — StreetCraft',
    ogDescription:
      'Turn new seasonal inventory unboxings and weekend clearance moments into packed fitting rooms and brisk register checkouts.',
  },
  eyebrow: 'FASHION, HOME & LIFESTYLE RETAIL',
  title: 'Retail, Boutiques & Lifestyle Stores',
  tagline: 'Turn new arrival unboxings and seasonal clearance moments into physical footfall.',
  description:
    'Independent fashion boutiques, curated homeware shops, and lifestyle retailers need to move inventory quickly without spending thousands on generic digital ads. StreetCraft coordinates new arrival drops, flash clearance sales, and VIP private previews across four local channels.',
  metrics: [
    {
      value: 'Unboxing Drops',
      label: 'New Collection Buzz',
      sublabel: 'Reel prompts and Story frames designed around fresh rack arrivals.',
    },
    {
      value: 'Weekend Clearance',
      label: 'Inventory Turnover Blitzes',
      sublabel: 'Time-sensitive markdown promotions to clear end-of-season racks.',
    },
    {
      value: 'Local Proximity',
      label: 'Neighborhood Discovery',
      sublabel: 'Captures local shoppers exploring physical high-street markets.',
    },
  ],
  heroCta: {
    primary: {
      label: 'Try Free Campaign Tool',
      href: '/free-tool',
    },
    secondary: {
      label: 'View Subscription Pricing',
      href: '/pricing',
    },
  },
  anatomy: {
    eyebrow: 'VERTICAL ANATOMY',
    title: 'How a Boutique Retail Campaign Operates in Practice',
    description:
      'From shipment unboxing to boutique checkout: an example of a coordinated new collection arrival promotion generated by StreetCraft.',
    previewTitle: 'New Arrival Unboxing Campaign Blueprint',
    previewType: 'recipe',
    items: [
      {
        badge: 'OPERATIONAL TRIGGER',
        label: 'Fresh Stock Arrival',
        text: 'New curated linen apparel collection or handmade ceramics shipment unboxed on Friday morning.',
        note: 'The ideal moment to create immediate exclusivity and weekend footfall.',
      },
      {
        badge: 'COLLECTION FOCUS',
        label: 'Signature Piece Highlight',
        text: 'Limited-edition handloom linen dresses and relaxed co-ord sets available in small batch sizes.',
        note: 'Injects your boutique’s curated aesthetic and price points automatically.',
      },
      {
        badge: '4-WAY EXECUTION',
        label: 'Coordinated Drop Blitz',
        text: 'Google Business product update + Instagram Reel unboxing prompt + WhatsApp VIP first-access alert + Fitting room & window card.',
        note: 'Synchronizes the entire boutique floor with your online audience.',
      },
    ],
  },
  capabilities: [
    {
      tag: 'NEW ARRIVALS',
      title: 'Fresh Shipment & Collection Drops',
      description:
        'Generate excitement around new rack arrivals with sensory fabric descriptions, styling tips, and limited-quantity urgency prompts.',
      bulletPoints: [
        'Curated piece highlights that explain craftsmanship and fabric details',
        'Direct Instagram Reel filming instructions for floor associates',
        'Landmark directions so new shoppers easily find your boutique door',
      ],
    },
    {
      tag: 'VIP ACCESS',
      title: 'Private Previews & Loyalty Evenings',
      description:
        'Reward top-spending regular clients with exclusive first-look access and private evening shopping slots before public launch.',
      bulletPoints: [
        'Exclusive WhatsApp invitation copy for high-value client lists',
        'Private styling session reservation triggers',
        'Personalized greeting tone that honors loyal shoppers',
      ],
    },
    {
      tag: 'CLEARANCE BLITZ',
      title: 'Weekend Flash Sales & Rack Turnover',
      description:
        'Clear out previous season inventory before new shipments arrive with urgent weekend markdown promotions across search and social.',
      bulletPoints: [
        'Tiered bundle savings promotions (e.g. Buy 2, Get 1 on clearance racks)',
        'Clear expiry deadlines (e.g. Saturday & Sunday only)',
        'Printable window posters and register cards ready in minutes',
      ],
    },
  ],
  playbook: [
    {
      step: 1,
      trigger: 'Inventory Shipment Unboxed',
      action: 'Select "New Collection Arrival" and input featured styles in StreetCraft.',
      outcome: 'Receive 4 synchronized marketing assets designed to drive immediate store visits.',
    },
    {
      step: 2,
      trigger: 'Launch VIP Broadcast',
      action: 'Send WhatsApp VIP first-look message to loyal clients before public announcement.',
      outcome: 'Top clients visit on Friday afternoon for early access fitting sessions.',
    },
    {
      step: 3,
      trigger: 'Public Weekend Push',
      action: 'Publish the Google Business update and post Instagram Reel unboxing framework.',
      outcome: 'Pulls weekend shoppers exploring the local high-street shopping district.',
    },
    {
      step: 4,
      trigger: 'Point-of-Sale Cross-Sell',
      action: 'Display the synchronized promotional card at checkout.',
      outcome: 'Encourages shoppers to add accessory items before final card swipe.',
    },
  ],
  closingCta: {
    eyebrow: 'GROW YOUR BOUTIQUE',
    title: 'Drive More Footfall to Your Retail Floor',
    description:
      'Generate your first coordinated boutique campaign pack across Google, Instagram, WhatsApp, and counter print in 60 seconds.',
    primaryCta: {
      label: 'Try Free Campaign Tool',
      href: '/free-tool',
    },
    secondaryCta: {
      label: 'View Subscription Pricing',
      href: '/pricing',
    },
  },
};
