import type { SolutionEditorialContent } from '../types';

export const salonsAndStudiosContent: SolutionEditorialContent = {
  category: 'BUSINESS SOLUTION',
  metadata: {
    title: 'Marketing Solution for Salons, Spas & Wellness Studios — StreetCraft',
    description:
      'Fill open midweek styling chairs, promote seasonal grooming packages, and reactivate dormant clients with coordinated 4-touchpoint local marketing.',
    ogTitle: 'Marketing for Salons & Wellness Studios — StreetCraft',
    ogDescription:
      'Turn slow weekday salon slots and seasonal hair/skin packages into fully booked appointment books and repeat client visits.',
  },
  eyebrow: 'BEAUTY, WELLNESS & GROOMING',
  title: 'Salons, Spas & Wellness Studios',
  tagline: 'Fill open stylist chairs during quiet weekday hours and reactivate regular clients.',
  description:
    'Salons and wellness studios frequently deal with peak weekend overcapacity alongside empty styling chairs from Monday through Thursday. StreetCraft provides salon owners with coordinated multi-channel appointment campaigns to maintain consistent chair utilization.',
  metrics: [
    {
      value: 'Mon – Thu',
      label: 'Midweek Appointment Boost',
      sublabel: 'Specifically designed to fill open weekday stylist and therapist slots.',
    },
    {
      value: 'VIP Retention',
      label: 'Client Reactivation Drops',
      sublabel: 'Direct WhatsApp alerts for regular hair, skin, and spa upkeep schedules.',
    },
    {
      value: 'Package Sync',
      label: 'Seasonal Treatment Bundles',
      sublabel: 'Monsoon hair spas, festive glow packages, and bridal trial promotions.',
    },
  ],
  heroCta: {
    primary: {
      label: 'Try Free Campaign Tool',
      href: '/free-tool',
    },
    secondary: {
      label: 'View Subscription Pricing',
      href: '/pricing',
    },
  },
  anatomy: {
    eyebrow: 'VERTICAL ANATOMY',
    title: 'How a Salon Campaign Operates in Practice',
    description:
      'From open appointment slots to confirmed chair bookings: an example of a coordinated weekday salon promotion generated by StreetCraft.',
    previewTitle: 'Midweek Keratin / Hair Spa Campaign Blueprint',
    previewType: 'recipe',
    items: [
      {
        badge: 'OPERATIONAL TRIGGER',
        label: 'Open Midweek Stylist Chairs',
        text: 'Wednesday & Thursday 11:00 AM – 4:00 PM quiet hours between morning blowouts and evening walk-ins.',
        note: 'The ideal window to schedule longer high-margin treatments.',
      },
      {
        badge: 'TREATMENT PACKAGE',
        label: 'Signature Wellness Package',
        text: 'Nourishing Deep Conditioning Hair Spa + Scalp Massage with a complimentary blow-dry finish.',
        note: 'Injects your salon’s premium hair/skin brands and services automatically.',
      },
      {
        badge: '4-WAY EXECUTION',
        label: 'Direct Booking Engine',
        text: 'Google Business offer update + Instagram Story transformation video cue + WhatsApp VIP client alert + Front desk display card.',
        note: 'Keeps receptionists and senior stylists aligned on the promotion.',
      },
    ],
  },
  capabilities: [
    {
      tag: 'CHAIR UTILIZATION',
      title: 'Midweek Slot Filling & Stylist Spotlights',
      description:
        'Target nearby residents and remote workers with special weekday pricing to fill stylist chairs during traditionally slow daytime hours.',
      bulletPoints: [
        'Weekday-only package terms to protect weekend premium pricing',
        'Direct WhatsApp "Book My Slot" messaging formulas',
        'Stylist spotlight introductions that build client trust',
      ],
    },
    {
      tag: 'CLIENT RETENTION',
      title: 'Seasonal Upkeep & Client Reactivation',
      description:
        'Reactivate regular clients due for their 6-week haircut, color root touch-up, or monthly facial with personalized, courteous broadcast reminders.',
      bulletPoints: [
        'Seasonal weather treatment packages (humidity defense, winter skin glow)',
        'VIP client exclusive discounts that prevent client churn',
        'Friendly neighborhood tone that feels personal, not automated',
      ],
    },
    {
      tag: 'BRIDAL & FESTIVAL',
      title: 'Festival Makeover & Bridal Booking Blitzes',
      description:
        'Launch coordinated booking windows for wedding season, festival glow packages, and Diwali/Eid grooming weeks before calendar deadlines.',
      bulletPoints: [
        'Advance booking deposit incentives',
        'Multi-service group booking packages',
        'Synchronized search, social, and salon mirror signage',
      ],
    },
  ],
  playbook: [
    {
      step: 1,
      trigger: 'Appointment Calendar Has Gaps',
      action: 'Select "Midweek Appointment Fill" and choose your signature treatment package in StreetCraft.',
      outcome: 'Receive 4 synchronized marketing assets with clear booking calls-to-action.',
    },
    {
      step: 2,
      trigger: 'Dispatch Broadcast',
      action: 'Send the formatted WhatsApp alert to your VIP client list and post the Instagram Story framework.',
      outcome: 'Clients reply directly to claim the open weekday slots.',
    },
    {
      step: 3,
      trigger: 'Appointment Service',
      action: 'Receptionist verifies the booking code and applies the treatment package terms.',
      outcome: 'Stylist delivers the service with complete operational clarity.',
    },
    {
      step: 4,
      trigger: 'Next Appointment Scheduled',
      action: 'Staff re-books the client for their 6-week follow-up at the front desk.',
      outcome: 'Turns a one-off slow-hour booking into a long-term recurring regular.',
    },
  ],
  closingCta: {
    eyebrow: 'GROW YOUR SALON',
    title: 'Keep Your Stylist Chairs Booked All Week',
    description:
      'Generate your first coordinated salon campaign pack across Google, Instagram, WhatsApp, and counter print in 60 seconds.',
    primaryCta: {
      label: 'Try Free Campaign Tool',
      href: '/free-tool',
    },
    secondaryCta: {
      label: 'View Subscription Pricing',
      href: '/pricing',
    },
  },
};
