import { FullCampaignPack, ChannelType } from '../types/campaign';

function saveBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function formatChannelText(channel: ChannelType, content: Record<string, any>): string {
  if (channel === 'GOOGLE_BUSINESS') {
    return `[GOOGLE BUSINESS UPDATE]\nHeadline: ${content.headline || ''}\n\n${content.body || ''}\n\nCall To Action: ${content.ctaType || 'Visit Us'} (${content.ctaValue || ''})\nOffer Summary: ${content.offerSummary || ''}`;
  }
  if (channel === 'INSTAGRAM') {
    const tags = Array.isArray(content.localTags) ? content.localTags.join(' ') : '';
    const frames = Array.isArray(content.storyFrames) ? content.storyFrames.map((f: string, i: number) => `Frame ${i + 1}: ${f}`).join('\n') : '';
    return `[INSTAGRAM REEL & STORY]\nReel Hook: ${content.reelHook || content.hook || ''}\n\nCaption:\n${content.caption || ''}\n\nStory Frames:\n${frames}\n\nDiscovery Tags:\n${tags}`;
  }
  if (channel === 'WHATSAPP') {
    return `[WHATSAPP BROADCAST]\n${content.broadcastMessage || ''}\n\nCall To Action: ${content.cta || ''}\nQuick Reply Preview: ${content.quickReplyPreview || ''}`;
  }
  if (channel === 'IN_STORE_POSTER') {
    return `[IN-STORE COUNTER CARD / POSTER]\nHeadline: ${content.headline || ''}\nSubheading: ${content.subheading || ''}\n\nBody:\n${content.body || ''}\n\nPerk Pill: ${content.offerPill || ''}\nScan Action: ${content.cta || 'Scan QR at Counter'}`;
  }
  return '';
}

export function formatChannelMarkdown(channel: ChannelType, content: Record<string, any>): string {
  if (channel === 'GOOGLE_BUSINESS') {
    return `### Google Business Update\n**Headline**: ${content.headline || ''}\n\n${content.body || ''}\n\n* **CTA**: ${content.ctaType || 'Visit Us'}\n* **Offer Summary**: ${content.offerSummary || ''}`;
  }
  if (channel === 'INSTAGRAM') {
    const tags = Array.isArray(content.localTags) ? content.localTags.join(' ') : '';
    const frames = Array.isArray(content.storyFrames) ? content.storyFrames.map((f: string, i: number) => `- **Frame ${i + 1}**: ${f}`).join('\n') : '';
    return `### Instagram Reel & Story\n> **Hook**: ${content.reelHook || content.hook || ''}\n\n**Caption**:\n${content.caption || ''}\n\n**Story Sequence**:\n${frames}\n\n**Hashtags**:\n\`${tags}\``;
  }
  if (channel === 'WHATSAPP') {
    return `### WhatsApp VIP Broadcast\n\`\`\`\n${content.broadcastMessage || ''}\n\`\`\`\n* **Action**: ${content.cta || ''}\n* **Quick Reply**: ${content.quickReplyPreview || ''}`;
  }
  if (channel === 'IN_STORE_POSTER') {
    return `### In-Store Counter Poster\n# ${content.headline || ''}\n## ${content.subheading || ''}\n\n${content.body || ''}\n\n**Badge**: \`${content.offerPill || ''}\`\n**QR Action**: *${content.cta || 'Scan to Redeem'}*`;
  }
  return '';
}

export function downloadChannelFile(
  channel: ChannelType,
  content: Record<string, any>,
  format: 'txt' | 'md' = 'txt'
) {
  const cleanName = channel.toLowerCase();
  if (format === 'md') {
    const md = formatChannelMarkdown(channel, content);
    saveBlob(md, `${cleanName}_proof.md`, 'text/markdown;charset=utf-8');
  } else {
    const txt = formatChannelText(channel, content);
    saveBlob(txt, `${cleanName}_proof.txt`, 'text/plain;charset=utf-8');
  }
}

export function downloadFullCampaignPackTxt(pack: FullCampaignPack, storeName: string = 'Store') {
  const { campaign, outputs } = pack;
  const divider = '================================================================';
  const subDivider = '----------------------------------------------------------------';

  const text = [
    divider,
    `STREETCRAFT CAMPAIGN PACK: ${campaign.offer.title || campaign.offer.description}`,
    `Store: ${storeName} | Type: ${campaign.type} | Created: ${new Date(campaign.createdAt).toLocaleDateString('en-IN')}`,
    `Timing: ${campaign.schedule.timingLabel || 'Active Window'}`,
    `Objective: ${campaign.objective} | Audience: ${campaign.audience || 'Neighborhood Customers'}`,
    divider,
    '',
    formatChannelText('GOOGLE_BUSINESS', outputs.googleBusiness as any),
    '',
    subDivider,
    '',
    formatChannelText('INSTAGRAM', outputs.instagram as any),
    '',
    subDivider,
    '',
    formatChannelText('WHATSAPP', outputs.whatsapp as any),
    '',
    subDivider,
    '',
    outputs.poster ? formatChannelText('IN_STORE_POSTER', outputs.poster as any) : '',
    '',
    divider,
    'Generated by StreetCraft — Physical Business Growth Engine',
    divider,
  ].filter(Boolean).join('\n');

  const slug = (campaign.offer.title || 'campaign').toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 30);
  saveBlob(text, `${slug}_campaign_pack.txt`, 'text/plain;charset=utf-8');
}

export function downloadFullCampaignPackMarkdown(pack: FullCampaignPack, storeName: string = 'Store') {
  const { campaign, outputs } = pack;

  const md = [
    `# StreetCraft Campaign Pack: ${campaign.offer.title || campaign.offer.description}`,
    `**Store**: ${storeName} &bull; **Type**: \`${campaign.type}\` &bull; **Timing**: ${campaign.schedule.timingLabel || 'Active Window'}`,
    `**Created**: ${new Date(campaign.createdAt).toLocaleDateString('en-IN')}`,
    '',
    '---',
    '',
    formatChannelMarkdown('GOOGLE_BUSINESS', outputs.googleBusiness as any),
    '',
    '---',
    '',
    formatChannelMarkdown('INSTAGRAM', outputs.instagram as any),
    '',
    '---',
    '',
    formatChannelMarkdown('WHATSAPP', outputs.whatsapp as any),
    '',
    '---',
    '',
    outputs.poster ? formatChannelMarkdown('IN_STORE_POSTER', outputs.poster as any) : '',
    '',
    '---',
    '*Generated by StreetCraft — Growth Engine for Physical Businesses*',
  ].filter(Boolean).join('\n');

  const slug = (campaign.offer.title || 'campaign').toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 30);
  saveBlob(md, `${slug}_campaign_pack.md`, 'text/markdown;charset=utf-8');
}

export function downloadFullCampaignPackJson(pack: FullCampaignPack) {
  const jsonStr = JSON.stringify(pack, null, 2);
  const slug = (pack.campaign.offer.title || 'campaign').toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 30);
  saveBlob(jsonStr, `${slug}_campaign_pack.json`, 'application/json;charset=utf-8');
}

export function triggerPrintPoster() {
  window.print();
}
